@startuml
class TechtonicsController {
    + InitialisePlates(TilePlateIn:GameObject[,], TileVertIn:GameObject[,], TileEdgeXIn:GameObject[,], TileEdgeYIn:GameObject[,]) : void
    + DetermineCollide(vector3:Vector3) : void
    + LtLcollide() : void
    + LtLDrift() : void
    + LtLSeperate() : void
    + OtLcollide() : void
    + OtLDrift() : void
    + OtLSeperate() : void
    + OtOcollide() : void
    + OtODrift() : void
    + OtOSeperate() : void
}
MonoBehaviour <|-- TechtonicsController
TechtonicsController --> "Selected" GameObject
@enduml
